/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imageMapperManager */

#ifndef _Included_imageMapperManager
#define _Included_imageMapperManager
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_ispd_mommybook_JniController_detectBookEdge(JNIEnv *, jclass clazz, jlong matAddrInput, jlong matAddrResult);
JNIEXPORT void JNICALL Java_com_ispd_mommybook_JniController_detectBookEdgeAndPDAlignment(JNIEnv *, jclass clazz, jlong matAddrInput, jlong matAddrResult, jint debugOption, jint curveFixOn);

//Get Matrix Info
JNIEXPORT jboolean JNICALL Java_com_ispd_mommybook_JniController_getCheckBookLocation(JNIEnv *env, jclass clazz);
JNIEXPORT void JNICALL Java_com_ispd_mommybook_JniController_getCropFourPoint(JNIEnv *env, jclass clazz, jfloatArray outFourPoints, jfloatArray outVerPoints);
JNIEXPORT jboolean JNICALL Java_com_ispd_mommybook_JniController_getCropMatrixValue(JNIEnv *env, jclass clazz, jfloatArray outCropMatValue,
                                                                                jint targetWidth, jint targetHeight);
JNIEXPORT jboolean JNICALL Java_com_ispd_mommybook_JniController_getAlignmentMatrixValue(JNIEnv *env, jclass clazz, jfloatArray outAlignLeftMat, jfloatArray outAlignRightMat,
                                                                                     jint targetWidth, jint targetHeight);
JNIEXPORT void JNICALL Java_com_ispd_mommybook_JniController_getAlignmentCurveValue(JNIEnv *env, jclass clazz, jfloatArray leftCurveValues, jfloatArray rightCurveValues);
JNIEXPORT void JNICALL Java_com_ispd_mommybook_JniController_setCurrentBookInfo(JNIEnv *env, jclass clazz, jint bookCoverIndex, jint bookPageIndex);

JNIEXPORT int JNICALL Java_com_ispd_mommybook_JniController_findKeyPointMatching(JNIEnv *, jclass clazz, jlong matAddrInput1, jlong matAddrInput2, int index);
JNIEXPORT int JNICALL Java_com_ispd_mommybook_JniController_findKeyPoint(JNIEnv *, jclass clazz, jlong matAddrInput1, int index);
JNIEXPORT float JNICALL Java_com_ispd_mommybook_JniController_findCircle(JNIEnv *, jclass clazz, jlong matAddrInput, jlong matAddrInput2, int index, int itemIndex, int useContour);

JNIEXPORT void JNICALL Java_com_ispd_mommybook_JniController_setTuneValues1ForCurve(JNIEnv *env, jobject,
                                                                                    jfloatArray curveTuneLeft1, jfloatArray curveTuneRight1,
                                                                                    jfloatArray curveTuneLeft2, jfloatArray curveTuneRight2,
                                                                                    jfloatArray curveTuneLeft3, jfloatArray curveTuneRight3,
                                                                                    jfloatArray curveTuneLeft4, jfloatArray curveTuneRight4,
                                                                                    jfloatArray curveTuneLeft5, jfloatArray curveTuneRight5);

JNIEXPORT void JNICALL Java_com_ispd_mommybook_JniController_setTuneValues2ForCurve(JNIEnv *env, jobject,
                                                                                    jfloatArray curveTuneLeft1, jfloatArray curveTuneRight1,
                                                                                    jfloatArray curveTuneLeft2, jfloatArray curveTuneRight2);

#ifdef __cplusplus
}
#endif
#endif
